# Generated by Django 4.2.28 on 2026-02-16 21:18

import children.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Assessment results in JSON format')),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment Category',
                'verbose_name_plural': 'Assessment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generated unique code', max_length=7, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dominant_hand', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=children.models.child_photo_path)),
                ('qr_code', models.CharField(editable=False, help_text='QR code data (same as code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_children', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='schools.school')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('face_view', 'Face View'), ('side_view', 'Side View'), ('back_view', 'Back View')], max_length=20)),
                ('photo', models.ImageField(upload_to=children.models.assessment_photo_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='children.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Photo',
                'verbose_name_plural': 'Assessment Photos',
                'ordering': ['photo_type'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='children.assessmentcategory'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='children.child'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['code'], name='children_ch_code_76990e_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['school'], name='children_ch_school__dd13ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentphoto',
            unique_together={('assessment', 'photo_type')},
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('child', 'category')},
        ),
    ]
